server:
  port: 8110

spring:
  datasource:
    url: jdbc:h2:mem:design # jdbc 链接 h2 的内存数据库 design
    driver-class-name: org.h2.Driver
    username: dev
    password: design
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update # auto update ddl
      dialect: org.hibernate.dialect.MySQL57Dialect
      show-sql: true
